version: '3'
services:
  app:
    image: pf-medicines-api-node-app
    container_name: pf-medicines-api-node-app
    cap_add:
      - 'SYS_ADMIN'
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'
    command: npm run start
    networks:
      - app
volumes:
  app:
networks:
  app:
    name: pf-medicines-api-node-app
