CREATE TABLE PUBLIC.PF_MED_FRECUENCY (
  MFRE_ID SERIAL PRIMARY KEY,
  MFRE_EVERY_HOURS NUMERIC NOT NULL,
  MFRE_QUANTITY NUMERIC NOT NULL
);

CREATE INDEX IDX_MED_FRECUENCY_EVERYHOURS ON PUBLIC.PF_MED_FRECUENCY (MFRE_EVERY_HOURS);
CREATE INDEX IDX_MED_FRECUENCY_QUANTITY ON PUBLIC.PF_MED_FRECUENCY (MFRE_QUANTITY);
CREATE UNIQUE INDEX IDX_MED_FRECUENCY_ALL ON PUBLIC.PF_MED_FRECUENCY (MFRE_EVERY_HOURS, MFRE_QUANTITY);
CREATE UNIQUE INDEX IDX_MED_FRECUENCY_ID ON PUBLIC.PF_MED_FRECUENCY (MFRE_ID);

CREATE TABLE PUBLIC.PF_MED_MANUFACTURER (
  MMAN_ID SERIAL PRIMARY KEY,
  MMAN_NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IDX_MED_MANUFACTURER_ID ON PUBLIC.PF_MED_MANUFACTURER (MMAN_ID);
CREATE UNIQUE INDEX IDX_MED_MANUFACTURER_NAME ON PUBLIC.PF_MED_MANUFACTURER (MMAN_NAME);

CREATE TABLE PUBLIC.PF_MED_SUBSTANCE (
  MSUB_ID SERIAL PRIMARY KEY,
  MSUB_NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IDX_MED_SUBSTANCE_ID ON PUBLIC.PF_MED_SUBSTANCE (MSUB_ID);
CREATE UNIQUE INDEX IDX_MED_SUBSTANCE_NAME ON PUBLIC.PF_MED_SUBSTANCE (MSUB_NAME);

CREATE TABLE PUBLIC.PF_USER (
  USER_ID SERIAL PRIMARY KEY,
  USER_NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IDX_USER_ID ON PUBLIC.PF_USER (USER_ID);
CREATE UNIQUE INDEX IDX_USER_NAME ON PUBLIC.PF_USER (USER_NAME);

CREATE TABLE PUBLIC.PF_MED_TYPE (
  MTYP_ID SERIAL PRIMARY KEY,
  MTYP_NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IDX_MED_TYPE_ID ON PUBLIC.PF_MED_TYPE (MTYP_ID);
CREATE UNIQUE INDEX IDX_MED_TYPE_NAME ON PUBLIC.PF_MED_TYPE (MTYP_NAME);

CREATE TABLE PUBLIC.PF_MED_BRANDED_MEDICINE (
  MBME_ID SERIAL PRIMARY KEY,
  MBME_NAME VARCHAR(255) NOT NULL,
  MTYP_ID INT NOT NULL REFERENCES PF_MED_TYPE(MTYP_ID),
  MMAN_ID INT NOT NULL REFERENCES PF_MED_MANUFACTURER(MMAN_ID)
);

CREATE INDEX IDX_MED_BRANDED_MEDICINE_MANUFACTURER ON PUBLIC.PF_MED_BRANDED_MEDICINE (MMAN_ID);
CREATE INDEX IDX_MED_BRANDED_MEDICINE_TYPE ON PUBLIC.PF_MED_BRANDED_MEDICINE (MTYP_ID);
CREATE UNIQUE INDEX IDX_MED_BRANDED_MEDICINE_ALL ON PUBLIC.PF_MED_BRANDED_MEDICINE (MBME_NAME, MTYP_ID, MMAN_ID);
CREATE UNIQUE INDEX IDX_MED_BRANDED_MEDICINE_ID ON PUBLIC.PF_MED_BRANDED_MEDICINE (MBME_ID);
CREATE UNIQUE INDEX IDX_MED_BRANDED_MEDICINE_NAME ON PUBLIC.PF_MED_BRANDED_MEDICINE (MBME_NAME);

CREATE TABLE PUBLIC.PF_MED_BRANDED_PRESENTATION (
  MBPR_ID SERIAL PRIMARY KEY,
  MBPR_QUANTITY NUMERIC NOT NULL,
  MBME_ID INT NOT NULL REFERENCES PF_MED_BRANDED_MEDICINE(MBME_ID),
  CONSTRAINT FK_BRANDED_PRESENTATION_BRANDED_MEDICINE FOREIGN KEY (MBME_ID) REFERENCES PF_MED_BRANDED_MEDICINE(MBME_ID)
);

CREATE INDEX IDX_MED_BRANDED_PRESENTATION_BRANDED_MEDICINE ON PUBLIC.PF_MED_BRANDED_PRESENTATION (MBME_ID);
CREATE UNIQUE INDEX IDX_MED_BRANDED_PRESENTATION_ALL ON PUBLIC.PF_MED_BRANDED_PRESENTATION (MBPR_QUANTITY, MBME_ID);
CREATE UNIQUE INDEX IDX_MED_BRANDED_PRESENTATION_ID ON PUBLIC.PF_MED_BRANDED_PRESENTATION (MBPR_ID);

CREATE TABLE PUBLIC.PF_MED_COMPONENT (
  MCOMP_ID SERIAL PRIMARY KEY,
  MCOMP_GRAMS NUMERIC NOT NULL,
  MSUB_ID INT NOT NULL REFERENCES PF_MED_SUBSTANCE(MSUB_ID),
  MBPR_ID INT NOT NULL REFERENCES PF_MED_BRANDED_PRESENTATION(MBPR_ID)
);

CREATE INDEX IDX_MED_COMPONENT_BRANDED_PRESENTATION ON PUBLIC.PF_MED_COMPONENT (MBPR_ID);
CREATE INDEX IDX_MED_COMPONENT_SUBSTANCE ON PUBLIC.PF_MED_COMPONENT (MSUB_ID);
CREATE UNIQUE INDEX IDX_MED_COMPONENT_ALL ON PUBLIC.PF_MED_COMPONENT (MCOMP_GRAMS, MSUB_ID, MBPR_ID);
CREATE UNIQUE INDEX IDX_MED_COMPONENT_ID ON PUBLIC.PF_MED_COMPONENT (MCOMP_ID);

CREATE TABLE PUBLIC.PF_MED_PRESCRIPTION (
  MPRE_ID SERIAL PRIMARY KEY,
  MPRE_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  MPRE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MPRE_IS_SELF_MEDICATED BOOLEAN NOT NULL DEFAULT TRUE,
  MTYP_ID INT NOT NULL REFERENCES PF_MED_TYPE(MTYP_ID),
  MFRE_ID INT NOT NULL REFERENCES PF_MED_FRECUENCY(MFRE_ID),
  USER_ID INT NOT NULL REFERENCES PF_USER(USER_ID)
);

CREATE INDEX IDX_MED_PRESCRIPTION_ACTIVE ON PUBLIC.PF_MED_PRESCRIPTION (MPRE_ACTIVE);
CREATE INDEX IDX_MED_PRESCRIPTION_DATE ON PUBLIC.PF_MED_PRESCRIPTION (MPRE_DATE);
CREATE INDEX IDX_MED_PRESCRIPTION_FREQUENCY ON PUBLIC.PF_MED_PRESCRIPTION (MFRE_ID);
CREATE INDEX IDX_MED_PRESCRIPTION_IS_SELF_MEDICATED ON PUBLIC.PF_MED_PRESCRIPTION (MPRE_IS_SELF_MEDICATED);
CREATE INDEX IDX_MED_PRESCRIPTION_TYPE ON PUBLIC.PF_MED_PRESCRIPTION (MTYP_ID);
CREATE INDEX IDX_MED_PRESCRIPTION_USER ON PUBLIC.PF_MED_PRESCRIPTION (USER_ID);
CREATE UNIQUE INDEX IDX_MED_PRESCRIPTION_ALL ON PUBLIC.PF_MED_PRESCRIPTION (MPRE_ACTIVE, MPRE_DATE, MPRE_IS_SELF_MEDICATED, MTYP_ID, MFRE_ID, USER_ID);
CREATE UNIQUE INDEX IDX_MED_PRESCRIPTION_ID ON PUBLIC.PF_MED_PRESCRIPTION (MPRE_ID);

CREATE TABLE PUBLIC.PF_MED_PURCHASE (
  MPUR_ID SERIAL PRIMARY KEY,
  MPUR_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MPUR_DISCOUNT NUMERIC NOT NULL,
  MPUR_PRICE NUMERIC NOT NULL,
  MPUR_SHIPPING_COST NUMERIC NOT NULL,
  MBPR_ID INT NOT NULL REFERENCES PF_MED_BRANDED_PRESENTATION(MBPR_ID),
  USER_ID INT NOT NULL REFERENCES PF_USER(USER_ID)
);

CREATE INDEX IDX_MED_PURCHASE_BRANDED_PRESENTATION ON PUBLIC.PF_MED_PURCHASE (MBPR_ID);
CREATE INDEX IDX_MED_PURCHASE_DATE ON PUBLIC.PF_MED_PURCHASE (MPUR_DATE);
CREATE INDEX IDX_MED_PURCHASE_DISCOUNT ON PUBLIC.PF_MED_PURCHASE (MPUR_DISCOUNT);
CREATE INDEX IDX_MED_PURCHASE_PRICE ON PUBLIC.PF_MED_PURCHASE (MPUR_PRICE);
CREATE INDEX IDX_MED_PURCHASE_SHIPPING_COST ON PUBLIC.PF_MED_PURCHASE (MPUR_SHIPPING_COST);
CREATE INDEX IDX_MED_PURCHASE_USER ON PUBLIC.PF_MED_PURCHASE (USER_ID);
CREATE UNIQUE INDEX IDX_MED_PURCHASE_ALL ON PUBLIC.PF_MED_PURCHASE (MPUR_DATE, MPUR_DISCOUNT, MPUR_PRICE, MPUR_SHIPPING_COST, MBPR_ID, USER_ID);
CREATE UNIQUE INDEX IDX_MED_PURCHASE_ID ON PUBLIC.PF_MED_PURCHASE (MPUR_ID);

CREATE TABLE PUBLIC.PF_MED_STOCK (
  MSTO_ID SERIAL PRIMARY KEY,
  MSTO_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MSTO_QUANTITY NUMERIC NOT NULL,
  MBPR_ID INT NOT NULL REFERENCES PF_MED_BRANDED_PRESENTATION(MBPR_ID),
  USER_ID INT NOT NULL REFERENCES PF_USER(USER_ID)
);

CREATE INDEX IDX_MED_STOCK_BRANDED_PRESENTATION ON PUBLIC.PF_MED_STOCK (MBPR_ID);
CREATE INDEX IDX_MED_STOCK_DATE ON PUBLIC.PF_MED_STOCK (MSTO_DATE);
CREATE INDEX IDX_MED_STOCK_QUANTITY ON PUBLIC.PF_MED_STOCK (MSTO_QUANTITY);
CREATE INDEX IDX_MED_STOCK_USER ON PUBLIC.PF_MED_STOCK (USER_ID);
CREATE UNIQUE INDEX IDX_MED_STOCK_ALL ON PUBLIC.PF_MED_STOCK (MSTO_DATE, MSTO_QUANTITY, MBPR_ID, USER_ID);
CREATE UNIQUE INDEX IDX_MED_STOCK_ID ON PUBLIC.PF_MED_STOCK (MSTO_ID);
